name: .NET

on:
  workflow_call:
    inputs:
      artifactNameOfCoverageCobertura:
        required: true
        type: string
      fail_below_min:
        required: false
        type: boolean
        description: 'Fail if overall Line Rate below lower threshold - true / false (default).'
        default: true
      thresholds:
        required: false
        type: string
        description: 'Threshold percentages for badge and health indicators, lower threshold can also be used to fail the action.'
        default: '60 80'

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    env:
      xmlFiles: TestResults/**/coverage.cobertura.xml    
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      id: download
      with:
        name: ${{ inputs.xmlFiles }}
        path: TestResults
    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.10
      with:
        reports: ${{ env.xmlFiles }}
        targetdir: coveragereport
        reporttypes: HtmlInline
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CoverageReport # Artifact name
        path: coveragereport # Directory containing files to upload        
    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ env.xmlFiles }}
        badge: true
        fail_below_min: ${{ inputs.fail_below_min }}
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: ${{ inputs.thresholds }}
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: always()
      with:
        recreate: true
        path: code-coverage-results.md
